# Generated by Django 3.2.20 on 2023-09-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230912_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bike_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brake',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charging_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='range_electric_mode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='range_pas_mode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tires',
        ),
    ]
